version: '3'

services:
    web:
      build:
        context: .
        dockerfile: ./docker/local/Dockerfile
      image: reactapp_image
      container_name: reactapp_container
      ports:
        - 3000:3000
      volumes:
        - ./:/app