name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/local/Dockerfile --tag oussama4/reactjs_image:${{ github.run_number }}

    - name: Push the Docker image to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push oussama4/reactjs_image:${{ github.run_number }}

    - name: Deploy to virtual machine
      uses: appleboy/ssh-action@master
      with:
        host: 20.51.236.83
        username: azureuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo docker pull oussama4/reactjs_image:${{ github.run_number }}
          sudo docker run -d --name my-container oussama4/reactjs_image:${{ github.run_number }}
